---
name: Class-Std-Fast_XS
version: 0.3
author:
  - 'Martin Kutter - MKUTTER@cpan.org'
abstract: speed up Class::Std::Fast by adding some XS code
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Std::Fast: 0.0.8
  perl: 5.8.0
provides:
  Class::Std::Fast_XS:
    file: lib/Class/Std/Fast_XS.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
